// ? computerPart & accessories
let monitors = [
  {
    id: 1,
    catName: "monitor",
    name: "benQ",
    model: "GW2780",
    size: "27-inch",
    price: "7960000",
    src: "./item-picture/GW2780.jpg",
  },
  {
    id: 2,
    catName: "monitor",
    name: "benQ",
    model: "XL2740",
    size: "27-inch",
    price: "20300000",
    src: "./item-picture/XL2740.jpg",
  },
  {
    id: 3,
    catName: "monitor",
    name: "benQ",
    model: "EW2480",
    size: "23.8-inch",
    price: "8110000",
    src: "./item-picture/EW2480.jpg",
  },
  {
    id: 4,
    catName: "monitor",
    name: "benQ",
    model: "EW3280U",
    size: "32-inch",
    price: "30600000",
    src: "./item-picture/EW3280U.jpg",
  },
  {
    id: 5,
    catName: "monitor",
    name: "ASUS",
    model: "VZ24EHE",
    size: "24-inch",
    price: "6200000",
    src: "./item-picture/VZ24EHE.jpg",
  },
  {
    id: 6,
    catName: "monitor",
    name: "ASUS",
    model: "VP228HI",
    size: "21.5-inch",
    price: "unavaible",
    src: "./item-picture/VP228HI.jpg",
  },
  {
    id: 7,
    catName: "monitor",
    name: "SAMSUNG",
    model: "S22A330",
    size: "22-inch",
    price: "3660000",
    src: "./item-picture/S22A330.jpg",
  },
  {
    id: 8,
    catName: "monitor",
    name: "SAMSUNG",
    model: "C310",
    size: "24-inch",
    price: "6900000",
    src: "./item-picture/C310.jpg",
  },
  {
    id: 9,
    catName: "monitor",
    name: "Gplus",
    model: "GDM-245LN",
    size: "24-inch",
    price: "4860000",
    src: "./item-picture/GDM-245LN.jpg",
  },
  {
    id: 10,
    catName: "monitor",
    name: "Gplus",
    model: "GDM-226LN",
    size: "22-inch",
    price: "4380000",
    src: "./item-picture/GDM-226LN.jpg",
  },
];
export { monitors };
